### PR TITLE
Fix filename with dots

### LINKED ISSUE #79: Filenames containing dots not working
For this given `docs` structure and this config
```
docs
├── index.en.md
├── index.md
├── topic1
│   ├── 1.1.exemple.en.md
│   ├── 1.1.exemple.fr.md
│   ├── index.en.md
│   └── index.fr.md
```

```
plugins:
  - i18n:
      default_language: fr
      languages:
        fr: Français
        en: English
```
I always get the english version : 

http://127.0.0.1:8000/Topic1/1.1.exemple.html => english (not ok)
http://127.0.0.1:8000/fr/Topic1/1.1.exemple.html => english (not ok)
http://127.0.0.1:8000/en/Topic1/1.1.exemple.html => english (ok)

### PR DESCRIPTION
**Pull request by brospars**
Closes #79

### CODE REVIEW

**Comment by ultrabug** [comment]
Bonjour Benoît,

Thanks for your contribution, I'll be reviewing it this week I promise!

**Comment by ultrabug** [comment]
I'm trying to update my tests to demonstrate the problem and the fix but while I'm able to reproduce the problem, the fix does not look good to me.

If I add the dot files in the current docs structure like this:

```
docs
├── image.en.fake
├── image.en.png
├── image.fr.fake
├── image.fr.png
├── index.fr.md
├── index.md
├── topic1
│   ├── named_file.en.md
│   └── named_file.fr.md
└── topic2
    ├── 1.1.filename.fr.html
    ├── 1.1.filename.html
    ├── README.en.md
    └── README.md
```

and apply your code to build it, I get

```
...
├── en
│   ├── image.fake
│   ├── image.png
│   ├── index.html
│   ├── topic1
│   │   └── named_file
│   │       └── index.html
│   └── topic2
│       ├── 1.1.1.filename.fr.html
│       ├── 1.1.1.filename.html
│       └── index.html
├── fr
│   ├── image.fake
│   ├── image.png
│   ├── index.html
│   ├── topic1
│   │   └── named_file
│   │       └── index.html
│   └── topic2
│       ├── 1.1.html
│       └── index.html
```

which does not look like what we want

I'll continue checking this out, but if you could provide a working test, that would be great

**Comment by ultrabug** [comment]
@brospars I worked on fixing this via #84 

Could you try it and report there please?

**Comment by brospars** [comment]
Yes I'll take a look. I may have miss some cases.

**Comment by ultrabug** [comment]
#84 does the work, closing; thanks again!

**Pull request closed without merging**
