### PR TITLE
[WIP]Add support  for --dirty and --dirtyreloead options

### PR DESCRIPTION
**Pull request by AngryMane**
Hi! I issued a PR once a long time ago.  Long time no see.🙂

# description
I found mkdocs supports incremental builds (--dirty and --dirtyreload options), but this plugin does not. 
This PR changes to support them.

# motivation 
If there are many documents, not supporting --dirty and --dirtyreload will cause extra time to build.
(For instance, my documents have been getting larger and larger, eventually taking as long as two minutes to hot reload!)
This PR allows hot reloads to be performed in a fraction of the time.

# remarks
Frankly, I think dirty flag should be passed from mkdocs. However, since it is currently not possible to obtain the flag from mkdocs, I implemented this by referencing sys.argv.

### CODE REVIEW

**Comment by AngryMane** [comment]
Thank you, I had missed it. I'll correct it. :smile:

**Comment by AngryMane** [comment]
Something is wrong with the behavior...
Only updates to the default language seem not to be hot reloaded.

**Comment by AngryMane** [comment]
I understood why the test failed. 
mkdocs make a cache for plugins if the plugin has "on_startup" or "on_shuddown" event. 
https://github.com/mkdocs/mkdocs/blob/79f17b4b71c73460c304e3281f6ff209788a76bf/mkdocs/config/config_options.py#L1128

This PR adds "on_startup" event, so mkdocs create plugin cache, and it causes  current_language parameter of one previous test case is left. This is the direct cause of test failed.

**Comment by ultrabug** [comment]
You're almost there @AngryMane ! Keep it up :)

**Comment by AngryMane** [comment]
OK. I fixed. But the commit log is a bit messy, so I'm going to create a new branch and re-create the PR, and close this PR.

**Pull request closed without merging**
