### PR TITLE
Fix/folder with tests

### LINKED ISSUE #288: Issue with incorrect language folder being copied
The contents of the mkdocs.yml file are as follows:

'''
site_name: 'Guide'
site_description: Documentation
docs_dir: docs/IDE/

extra_css:
  - stylesheets/extra.css

theme:
    name: material
    features:
      - content.tooltips
      - navigation.tracking
      - navigation.expand
      - content.code.copy
      - content.code.select
      - content.code.annotate
      - content.footnote.tooltips

    palette:
      # Palette toggle for automatic mode
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default 
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/github
      link: site
    - icon: fontawesome/brands/slack
      link: site
  tags:
    <tag>: <identifier>
  generator: true

markdown_extensions: 
  - meta
  - footnotes
  - attr_list
  - abbr
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - tables
  - admonition
  - def_list
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - tags
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
        - locale: ko
          name: Korean
          build: true
          default: true
        - locale: ja
          name: Japan
          build: true`

The folder structure is as follows:

docs / ko / index.md
                   ko_folder / ko_index.md
            en / index.md
                   en_folder / en_index.md
            ja / index.md
                  ja_folder / ja_index.md
'''
               
When you do mkdocs build, the ko folder is copied to each of the en and ja folders in the site folder.
ex)
site / ko_index.md
         a folder / ko_index.md
         en / en_index.md
                   en_folder / en_index.md
                   ko_folder / ko_index.md
         ja / index.md
                  ja_folder / ja_index.md
                  ko_folder / ko_index.md

What's the problem?

- mkdocs version : 1.5.3
- python version : 3.7.4
- mkdocs-static-i18n version : 1.2.1

### PR DESCRIPTION
**Pull request by kamilkrzyskow**
For now it's WIP as I couldn't really reproduce the incorrect file lookup in #288
I added tests with WARNING capture, to also handle #277 and with that I found issues concerning `Could not find a homepage for locale 'en'` in `use_directory_urls=False` tests.

Sorry it's taking so long @ultrabug the issue is a bit tricky for me, but I hope I'll finish it tomorrow.

EDIT:
After further debug process I consider #288 requires a config change by the user, and therefore the PR won't affect it.

### CODE REVIEW

**Comment by kamilkrzyskow** [comment]
I did a bit more debugging with the custom docs and found out that `reversed` breaks in the `nav` processing when there is a user defined `nav` in the docs, because the user defines the `nav` with paths without the language prefix. However, despite the wrong file being loaded for `bot/selfhosting.md` for `de_CH` in the `nav` processing, the website works fine and everything works as expected 😓 As in the navigation link properly resolves the `de_CH` version of the `bot/selfhosting.md` file.

<details> 
<summary> Excerpt of the debug.log </summary>

```py
Nav (C:\MyFiles\PythonVENV\Lib\site-packages\mkdocs\structure\nav.py):
input_path=bot/selfhosting.md
-- get_file_from_path --
path='bot/selfhosting.md'
current en
is_relative_to(bot\selfhosting.md, en) -> False
default en
is_relative_to(bot\selfhosting.md, en) -> False
reversed(expected_src_uris):
0 bot\selfhosting.md
1 en\bot\selfhosting.md
2 en\bot\selfhosting.md

TreeProcessor (C:\MyFiles\PythonVENV\Lib\site-packages\mkdocs\structure\pages.py):
input_path=en/bot/selfhosting.md
src_path=en/bot/index.md
-- get_file_from_path --
path='en/bot/selfhosting.md'
current en
is_relative_to(en\bot\selfhosting.md, en) -> True
default en
is_relative_to(en\bot\selfhosting.md, en) -> True
reversed(expected_src_uris):
0 en\bot\selfhosting.md
1 en\en\bot\selfhosting.md
2 en\bot\selfhosting.md
3 bot\selfhosting.md

Nav (C:\MyFiles\PythonVENV\Lib\site-packages\mkdocs\structure\nav.py):
input_path=bot/selfhosting.md
-- get_file_from_path --
path='bot/selfhosting.md'
current de_CH
is_relative_to(bot\selfhosting.md, de_CH) -> False
default en
is_relative_to(bot\selfhosting.md, en) -> False
reversed(expected_src_uris):
0 bot\selfhosting.md
1 en\bot\selfhosting.md
2 de_CH\bot\selfhosting.md

TreeProcessor (C:\MyFiles\PythonVENV\Lib\site-packages\mkdocs\structure\pages.py):
input_path=de_CH/bot/selfhosting.md
src_path=de_CH/bot/index.md
-- get_file_from_path --
path='de_CH/bot/selfhosting.md'
current de_CH
is_relative_to(de_CH\bot\selfhosting.md, de_CH) -> True
default en
is_relative_to(de_CH\bot\selfhosting.md, en) -> False
reversed(expected_src_uris):
0 de_CH\bot\selfhosting.md
1 en\de_CH\bot\selfhosting.md
2 en\bot\selfhosting.md
3 bot\selfhosting.md

TreeProcessor (C:\MyFiles\PythonVENV\Lib\site-packages\mkdocs\structure\pages.py):
input_path=de_CH/legal/website.md
src_path=de_CH/legal/index.md
-- get_file_from_path --
path='de_CH/legal/website.md'
current de_CH
is_relative_to(de_CH\legal\website.md, de_CH) -> True
default en
is_relative_to(de_CH\legal\website.md, en) -> False
reversed(expected_src_uris):
0 de_CH\legal\website.md
1 en\de_CH\legal\website.md
2 en\legal\website.md
3 legal\website.md
```

</details>

**Comment by kamilkrzyskow** [comment]
The current setup fixes the issues with the file lookup during the nav processing, but I compared the built site with this fix and the previous 1.2.1 commit and both file structures and contents are identical. So I can't figure out what was the issue with https://github.com/ultrabug/mkdocs-static-i18n/issues/288 so I have to wait for more feedback.

**Comment by kamilkrzyskow** [comment]
Almost took a week 😮‍💨 @ultrabug it's ready for the review. 
As written before, it turned out there was no issue with the file lookup 😓, so the removal of the 1.2.1 release was unnecessary.
My confusion in this comment https://github.com/ultrabug/mkdocs-static-i18n/issues/288#issuecomment-1915252000 came from the mixed behaviour as described in https://github.com/ultrabug/mkdocs-static-i18n/pull/290#issuecomment-1922001828
The Navigation and TreeProcessor passed different values to the `get_file_from_path` function depending on the existence of the `nav` in the `mkdocs.yml` file, and it changed the output of the print debug logs I added.

My main error was I didn't check what file actually got returned from the function I just looked at the order of the resolved expected URL list😓and actually the correct file was returned.
Here are 2 very simple logs of the output (source_path, expected_url_index, returned file), you can see that the new "fixed" log has lower index values than the previous one, so there is an improvement, perhaps it's bigger with docs that use more languages.

Adding the folder structure tests I increased strictness of them too, to detect warnings early, doing that revealed an issue with the `use_directory_urls: false` setting, which couldn't resolve the homepage for the default language.

So my lacking debug progress escalated a non-issue to a critical one, however the overall trial and error process wasn't pointless or fruitless as in the end I consider the plugin got improved :v:

**Comment by ultrabug** [comment]
Once again, thank you for your tenacity

**Comment by kamilkrzyskow** [comment]
@ultrabug Thanks for the merge but when will you release a new version?

**Comment by ultrabug** [comment]
Once #293 is in I'll release a new version

**Comment by ultrabug** [comment]
done! 1.2.2 is out!

**Pull request merged**
