### PR TITLE
allow localized content to diverge from the default one

### PR DESCRIPTION
**Pull request by ultrabug**
as per #57, we should allow localized versions to have pages and
assets that do not exist on the default language

### CODE REVIEW

**Comment by ultrabug** [comment]
tests are inconsistent, I'll have to dig into that

**Comment by skullydazed** [comment]
Thanks for putting this together! I was hoping to have tried it out by now but haven't been able to squeeze out the time yet. I should be able to in the next day or two.

**Comment by ultrabug** [comment]
No problem mate, shout when the time is right for you :+1:

**Comment by skullydazed** [comment]
I had a chance to play with this tonight. Here is the branch I'm working in: https://github.com/qmk/qmk_mkdocs/tree/mkdocs-static-i18n

Basic functionality seems to work fine, but `mkdocs serve` is a little... finicky? Sometimes page loads take a long time and it's not clear to me why.

I added 3 files: faq.fr.md  faq.he.md  faq.zh.md

All 3 of these work now, both with `mkdocs serve` and `mkdocs build`.

**Comment by ultrabug** [comment]
>  Sometimes page loads take a long time and it's not clear to me why.

I do not experience this sorry

I'm inclined to merge and release this feature if that's okay with you?

**Comment by skullydazed** [comment]
> I do not experience this sorry

I'm able to replicate it even without this PR. Not sure if it's a cache issue or what exactly, but at least it's not related.

> I'm inclined to merge and release this feature if that's okay with you?

Sounds good to me.

**Comment by ultrabug** [comment]
Thanks

**Pull request merged**
