### PR TITLE
add default_language_only option to build default language only

### PR DESCRIPTION
**Pull request by ultrabug**
see issue #32 for more details

### CODE REVIEW

**Comment by ultrabug** [comment]
cc @stanzilla could you try this and report back please?

**Comment by Stanzilla** [comment]
Okay so I tested it and something seems to be not quite right:

`mkdocs build` with:

```yml
   - i18n:
       default_language: !ENV [DEFAULT_LANGUAGE, "en"]
       default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, true]
       languages:
         fr: Français (Beta)  
```

52.3 seconds

and with the plugin commented out fully it's 17.06s

**Comment by ultrabug** [comment]
> Okay so I tested it and something seems to be not quite right:

Can you show the exact command you used and the build output?

**Comment by Stanzilla** [comment]
> > Okay so I tested it and something seems to be not quite right:
> 
> Can you show the exact command you used and the build output?

Yes, sir. 

image

**Comment by ultrabug** [comment]
Very interesting, what about the time to build the whole site, languages included?

**Comment by Stanzilla** [comment]
> Very interesting, what about the time to build the whole site, languages included?

77.59s with 

```yml
      default_language: en
      default_language_only: false
      languages:
        fr: Français (Beta)
```

**Comment by ultrabug** [comment]
Ok so it's better, but not enough ahah, let me think about it

**Comment by ultrabug** [comment]
Ok @Stanzilla try again please, that should be way better now

**Comment by Stanzilla** [comment]
> Ok @Stanzilla try again please, that should be way better now

28.75s!

**Comment by ultrabug** [comment]
Does that count as a green light? ;)

**Comment by Stanzilla** [comment]
> Does that count as a green light? ;)

I think so! I mean it's still an extra 10s but that is only on the first run of `serve` and for a full build I don't care as much since it is running in CI. I will test drive it some more and see if my contributors complain again :)

Thank you so much for the very quick turnaround on this!

**Pull request merged**
