### PR TITLE
Add support for localized static pages

### PR DESCRIPTION
**Pull request by ultrabug**
As per issue #22 request this PR adds support to localize all the things :smile_cat: 

- **no added configuration parameter**, any file with `.<locale>.<suffix>` will be considered as a translation file

While I worked on this I figured out that we could also offer our users to reference their links and assets in their markdown sources without the need to add their localized suffix!

This will greatly simplify things as we now only have to focus on the content and not worry about the image or markdown link names : whenever a translated version is available, it will be used instead of the default one.

I demonstrate this by adding a localized version of an image in the demo site:
- it is displayed in english in the default + en versions
- it is displayed in french in the french version
- **AND** it is referenced without its language suffix in the markdown source with a simple `[localized image](image.png)`

### CODE REVIEW

**Comment by ultrabug** [comment]
@magneticcore @zLucPlayZ could you please test this and report back please?

Also, @Stanzilla I guess I now can reconsider [my comment here](https://github.com/ultrabug/mkdocs-static-i18n/issues/20#issuecomment-817950350) as the added feature can handle this for you too. That might be something interesting for you!

**Comment by Stanzilla** [comment]
Oh awesome, I'll check it out

**Comment by ultrabug** [comment]
I adapted the tests + reworked the whole demo website to showcase and explain everything better

I'd love some feedback guys tho I'm confident this works as expected. Will merge on Sunday otherwise so I can address the other requests.

**Comment by zLucPlayZ** [comment]
After testing in a couple different setups and usages, seems to work fine. I will continue testing.
If I encounter anything until you decide to merge, I will report back right away.

**Comment by Stanzilla** [comment]
I did a brief test and it did not generate the URLs in markdown correctly, ended up with `http://127.0.0.1:8000/fr/getting_started/publishing_checklist/publishing.md` instead of `http://127.0.0.1:8000/fr/getting_started/publishing/` when using `[Publishing on Core](publishing.md)`. I might have to try a newer version of `mkdocs-autolinks-plugin`, I had to downgrade that because of issues, am on `0.3.0` atm. Which version did you test with?

**Comment by ultrabug** [comment]
@Stanzilla I'm a bit puzzled by what you say because my structure tests have not moved an inch.

Your comment mention `/fr/getting_started/publishing_checklist/publishing.md` and `/fr/getting_started/publishing/`, where is that `publishing_checklist` gone? Did you misread something maybe?

I do not test this plugin with the combination of any other plugin so I did no check what `mkdocs-autolinks-plugin` has to say about that and I'm not in favor of coding magic to trick other plugins anyway.

If you want to discuss how to fix `mkdocs-autolinks-plugin` or make it play nice with `mkdocs-static-i18n` I suggest you open an issue either here or on the autolinks repo and ping me?

**Comment by ultrabug** [comment]
merged #25 here

**Comment by ultrabug** [comment]
@Stanzilla I tried quickly by pulling latest `development` branch of the `platform-documentation` and uncommented the i18n plugin. The structure looks fine to me:

```
site/fr/getting_started
├── backups
│   └── index.html
├── community_content
│   └── index.html
├── core_help
│   └── index.html
├── editor_intro
│   └── index.html
├── installing_core
│   └── index.html
├── my_first_multiplayer_game
│   └── index.html
├── performance_panel
│   └── index.html
├── profiler
│   └── index.html
├── project_files
│   └── index.html
├── publishing
│   └── index.html
├── publishing_checklist
│   └── index.html
└── start
    └── index.html
```

Also, it's interesting to see that with this MR the localized build is smarter and you get **less** warnings about missing translation files:

before 

```
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - icons.md
              - index.fr.md
              - generated/tags.md
              - getting_started/community_content.fr.md
              - getting_started/core_help.fr.md
              - getting_started/editor_intro.fr.md
              - getting_started/installing_core.fr.md
              - getting_started/my_first_multiplayer_game.fr.md
              - getting_started/performance_panel.fr.md
              - getting_started/profiler.fr.md
              - getting_started/publishing.fr.md
              - getting_started/publishing_checklist.fr.md
              - tutorials/ui_tutorial.md
              - generated/tags.md
```

after

```
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - icons.md
              - generated/tags.md
              - tutorials/ui_tutorial.md
```

So I'm gonna go ahead and release this.

**Comment by Stanzilla** [comment]
Okay great, I'm going to test more and report back, for now assume it was a bug on my side :)

**Pull request merged**
