### PR TITLE
Add theme specific files during on_post_build #35

### PR DESCRIPTION
**Pull request by adamkusmirek**
Analogous to the build command implementation in mkdocs:
load theme env and use it to add theme related files to the filelist

### CODE REVIEW

**Comment by adamkusmirek** [comment]
Some tests are to follow before setting to ready for review

**Comment by ultrabug** [comment]
Please be reminded to use `make qa` before committing, CI enforces linters

**Comment by ultrabug** [comment]
@adamkusmirek do you need help to get this in?

**Comment by Stanzilla** [comment]
@ultrabug I think you need to approve the CI workflow since they are a first time contributor

**Comment by adamkusmirek** [comment]
Ok, I added one testcase where I check if the same font files are being generated as in the base config case.
It checks specifically the case where the readthedocs theme has been added.

I hope that is sufficient, feel free to suggest/add more tests that could be done.

I tried my best to stick to your code style/structure.

**Comment by adamkusmirek** [comment]
> @ultrabug I think you need to approve the CI workflow since they are a first time contributor

indeed, Stanzilla is correct

**Comment by ultrabug** [comment]
Brilliant, thanks a lot @adamkusmirek 

Special shout out to @Stanzilla as well :+1:

**Comment by ultrabug** [comment]
like the plugin @adamkusmirek ? consider giving it a :star: to spread the :heart:

**Pull request merged**
