### PR TITLE
post_build: support explicitly mkdocs-awesome-pages-plugin nav

### PR DESCRIPTION
**Pull request by ultrabug**
do not recursively call 'on_nav' to fix issue #65

this makes this plugin and the awesome-pages one 100% compatible
thanks to @phasel74, @scmcca and of course @lukasgeiter

### CODE REVIEW

**Comment by ultrabug** [comment]
@scmcca @lukasgeiter @phasel74 would you please check and test this PR? I believe I found a way to fix the problem after all thanks to Lukas help.

**Comment by scmcca** [comment]
Thanks for taking care of this so quickly! 

I'd love to test this out, but I'm somewhat new to this. Any hints on how I could use the changes made here to the plugin in my project? Much appreciated!

**Comment by lukasgeiter** [comment]
This doesn't really work for me. For example in this simple scenario, `Page 1` doesn't get translated:

```yml
site_name: Test
theme: material
plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
      nav_translations:
        de:
          Page 1: Seite 1
  - awesome-pages


nav:
  - Page 1: page1.md
```

This can probably be fixed... However, I also noticed a conceptual issue with the current approach. Right now, you translate the navigation first, and then run it through awesome-pages. This should work in some cases, but doesn't hold up for all of them. 

For example, my plugin allows users to set titles (for sections, pages and links) in `.pages` files placed anywhere in the `docs` directory. But because the translation phase happens before awesome-pages does its thing, these custom titles cannot be translated.

---

To understand the problem better, I have a question for you: Is the structure of the navigation the same in all languages or can it be different? Meaning, can it be that one language has a nav item that the other does not?

**Comment by ultrabug** [comment]
> To understand the problem better, I have a question for you: Is the structure of the navigation the same in all languages or can it be different? Meaning, can it be that one language has a nav item that the other does not?

It can be different yes, so I have to deal with a nav per language. As a matter a fact, I do have to create a config, a files and a nav for each language.

**Comment by ultrabug** [comment]
version 2.6.1 of awesome-pages plugin fixed the issue; I'm closing here and will add a warning on i18n plugin if used with awesome-pages < 2.6.1

**Pull request closed without merging**
